### ISSUE TITLE
docker-compose file issue network-mode

### ISSUE THREAD

**Issue by AngieLarkin** [javadmohebbi/goNfCollector#7]
error while docker-compose up -d
````
ERROR: for oi24_nfcolector_1  "host" network_mode is incompatible with port_bindings

ERROR: for nfcolector  "host" network_mode is incompatible with port_bindings
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 203, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 1186, in up
  File "compose/cli/main.py", line 1182, in up
  File "compose/project.py", line 702, in up
  File "compose/parallel.py", line 108, in parallel_execute
  File "compose/parallel.py", line 206, in producer
  File "compose/project.py", line 688, in do
  File "compose/service.py", line 564, in execute_convergence_plan
  File "compose/service.py", line 480, in _execute_convergence_create
  File "compose/parallel.py", line 108, in parallel_execute
  File "compose/parallel.py", line 206, in producer
  File "compose/service.py", line 478, in <lambda>
  File "compose/service.py", line 457, in create_and_start
  File "compose/service.py", line 334, in create_container
  File "compose/service.py", line 941, in _get_container_create_options
  File "compose/service.py", line 1073, in _get_container_host_config
  File "docker/api/container.py", line 598, in create_host_config
  File "docker/types/containers.py", line 339, in __init__
docker.errors.InvalidArgument: "host" network_mode is incompatible with port_bindings
````

looks like incorrect usage of network_mode, apparently it still has to be networks?

**Comment by javadmohebbi** [comment]
Hi @AngieLarkin 

Please fix it using [this solution](https://github.com/javadmohebbi/goNfCollector/issues/3#issuecomment-826095732)
